apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../platform-agnostic/minio
- ../platform-agnostic/mysql
- ../../base/argo
- ../../base/pipeline
- ../../base/metadata

resources:
- namespace.yaml

namespace: kubeflow

images:
- name: mysql
  newTag: "5.6"
- name: minio/minio
  newTag: RELEASE.2018-02-09T22-40-05Z

configMapGenerator:
- name: pipeline-install-config
  env: params.env

secretGenerator:
- name: mysql-secret
  env: params-db-secret.env

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: kfp-namespace
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: ml-pipeline
- fieldref:
    fieldPath: data.bucketName
  name: kfp-artifact-bucket-name
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: pipeline-install-config
- fieldref:
    fieldPath: data.containerRuntimeExecutor
  name: kfp-container-runtime-executor
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: pipeline-install-config

configurations:
- params.yaml
