// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend/api/resource_reference.proto

package go_client // import "github.com/kubeflow/pipelines/backend/api/go_client"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResourceType int32

const (
	ResourceType_UNKNOWN_RESOURCE_TYPE ResourceType = 0
	ResourceType_EXPERIMENT            ResourceType = 1
	ResourceType_JOB                   ResourceType = 2
	ResourceType_PIPELINE              ResourceType = 3
	ResourceType_PIPELINE_VERSION      ResourceType = 4
	ResourceType_NAMESPACE             ResourceType = 5
	ResourceType_USER                  ResourceType = 6
)

var ResourceType_name = map[int32]string{
	0: "UNKNOWN_RESOURCE_TYPE",
	1: "EXPERIMENT",
	2: "JOB",
	3: "PIPELINE",
	4: "PIPELINE_VERSION",
	5: "NAMESPACE",
	6: "USER",
}
var ResourceType_value = map[string]int32{
	"UNKNOWN_RESOURCE_TYPE": 0,
	"EXPERIMENT":            1,
	"JOB":                   2,
	"PIPELINE":              3,
	"PIPELINE_VERSION":      4,
	"NAMESPACE":             5,
	"USER":                  6,
}

func (x ResourceType) String() string {
	return proto.EnumName(ResourceType_name, int32(x))
}
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_resource_reference_109930b442aefc2a, []int{0}
}

type Relationship int32

const (
	Relationship_UNKNOWN_RELATIONSHIP Relationship = 0
	Relationship_OWNER                Relationship = 1
	Relationship_CREATOR              Relationship = 2
)

var Relationship_name = map[int32]string{
	0: "UNKNOWN_RELATIONSHIP",
	1: "OWNER",
	2: "CREATOR",
}
var Relationship_value = map[string]int32{
	"UNKNOWN_RELATIONSHIP": 0,
	"OWNER":                1,
	"CREATOR":              2,
}

func (x Relationship) String() string {
	return proto.EnumName(Relationship_name, int32(x))
}
func (Relationship) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_resource_reference_109930b442aefc2a, []int{1}
}

type ResourceKey struct {
	Type                 ResourceType `protobuf:"varint,1,opt,name=type,proto3,enum=api.ResourceType" json:"type,omitempty"`
	Id                   string       `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ResourceKey) Reset()         { *m = ResourceKey{} }
func (m *ResourceKey) String() string { return proto.CompactTextString(m) }
func (*ResourceKey) ProtoMessage()    {}
func (*ResourceKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_reference_109930b442aefc2a, []int{0}
}
func (m *ResourceKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceKey.Unmarshal(m, b)
}
func (m *ResourceKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceKey.Marshal(b, m, deterministic)
}
func (dst *ResourceKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceKey.Merge(dst, src)
}
func (m *ResourceKey) XXX_Size() int {
	return xxx_messageInfo_ResourceKey.Size(m)
}
func (m *ResourceKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceKey.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceKey proto.InternalMessageInfo

func (m *ResourceKey) GetType() ResourceType {
	if m != nil {
		return m.Type
	}
	return ResourceType_UNKNOWN_RESOURCE_TYPE
}

func (m *ResourceKey) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ResourceReference struct {
	Key                  *ResourceKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name                 string       `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Relationship         Relationship `protobuf:"varint,2,opt,name=relationship,proto3,enum=api.Relationship" json:"relationship,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ResourceReference) Reset()         { *m = ResourceReference{} }
func (m *ResourceReference) String() string { return proto.CompactTextString(m) }
func (*ResourceReference) ProtoMessage()    {}
func (*ResourceReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_reference_109930b442aefc2a, []int{1}
}
func (m *ResourceReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceReference.Unmarshal(m, b)
}
func (m *ResourceReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceReference.Marshal(b, m, deterministic)
}
func (dst *ResourceReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceReference.Merge(dst, src)
}
func (m *ResourceReference) XXX_Size() int {
	return xxx_messageInfo_ResourceReference.Size(m)
}
func (m *ResourceReference) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceReference.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceReference proto.InternalMessageInfo

func (m *ResourceReference) GetKey() *ResourceKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ResourceReference) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResourceReference) GetRelationship() Relationship {
	if m != nil {
		return m.Relationship
	}
	return Relationship_UNKNOWN_RELATIONSHIP
}

func init() {
	proto.RegisterType((*ResourceKey)(nil), "api.ResourceKey")
	proto.RegisterType((*ResourceReference)(nil), "api.ResourceReference")
	proto.RegisterEnum("api.ResourceType", ResourceType_name, ResourceType_value)
	proto.RegisterEnum("api.Relationship", Relationship_name, Relationship_value)
}

func init() {
	proto.RegisterFile("backend/api/resource_reference.proto", fileDescriptor_resource_reference_109930b442aefc2a)
}

var fileDescriptor_resource_reference_109930b442aefc2a = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xdf, 0x6b, 0x9c, 0x40,
	0x14, 0x85, 0xa3, 0x6e, 0x7e, 0xec, 0xdd, 0xed, 0x32, 0xb9, 0xa4, 0x60, 0xdf, 0xc2, 0xd2, 0x42,
	0xc8, 0x83, 0x42, 0x42, 0xde, 0x6b, 0xb6, 0x03, 0xb5, 0x9b, 0x8c, 0x32, 0xba, 0x4d, 0xdb, 0x17,
	0x51, 0xf7, 0x26, 0x19, 0xd6, 0xe8, 0xe0, 0xba, 0x14, 0x9f, 0x0a, 0xfd, 0xcb, 0x4b, 0xa4, 0x62,
	0xf6, 0x6d, 0x86, 0xef, 0x70, 0xee, 0x07, 0x07, 0x3e, 0x66, 0x69, 0xbe, 0xa1, 0x72, 0xed, 0xa6,
	0x5a, 0xb9, 0x35, 0x6d, 0xab, 0x5d, 0x9d, 0x53, 0x52, 0xd3, 0x23, 0xd5, 0x54, 0xe6, 0xe4, 0xe8,
	0xba, 0x6a, 0x2a, 0xb4, 0x52, 0xad, 0xe6, 0x5f, 0x60, 0x22, 0xff, 0x07, 0x96, 0xd4, 0xe2, 0x27,
	0x18, 0x35, 0xad, 0x26, 0xdb, 0x38, 0x37, 0x2e, 0x66, 0x57, 0xa7, 0x4e, 0xaa, 0x95, 0xd3, 0xf3,
	0xb8, 0xd5, 0x24, 0x3b, 0x8c, 0x33, 0x30, 0xd5, 0xda, 0x36, 0xcf, 0x8d, 0x8b, 0xb1, 0x34, 0xd5,
	0x7a, 0xfe, 0xd7, 0x80, 0xd3, 0x3e, 0x26, 0xfb, 0x33, 0x38, 0x07, 0x6b, 0x43, 0x6d, 0xd7, 0x35,
	0xb9, 0x62, 0x7b, 0x5d, 0x4b, 0x6a, 0xe5, 0x2b, 0x44, 0x84, 0x51, 0x99, 0xbe, 0x90, 0x6d, 0x75,
	0x5d, 0xdd, 0x1b, 0x6f, 0x60, 0x5a, 0x53, 0x91, 0x36, 0xaa, 0x2a, 0xb7, 0xcf, 0x4a, 0x77, 0x77,
	0x06, 0x99, 0x01, 0xc8, 0xbd, 0xd8, 0xe5, 0x1f, 0x98, 0xbe, 0x55, 0xc5, 0x0f, 0xf0, 0x7e, 0x25,
	0x96, 0x22, 0x78, 0x10, 0x89, 0xe4, 0x51, 0xb0, 0x92, 0x0b, 0x9e, 0xc4, 0x3f, 0x43, 0xce, 0x0e,
	0x70, 0x06, 0xc0, 0x7f, 0x84, 0x5c, 0xfa, 0xf7, 0x5c, 0xc4, 0xcc, 0xc0, 0x63, 0xb0, 0xbe, 0x05,
	0xb7, 0xcc, 0xc4, 0x29, 0x9c, 0x84, 0x7e, 0xc8, 0xef, 0x7c, 0xc1, 0x99, 0x85, 0x67, 0xc0, 0xfa,
	0x5f, 0xf2, 0x9d, 0xcb, 0xc8, 0x0f, 0x04, 0x1b, 0xe1, 0x3b, 0x18, 0x0b, 0xef, 0x9e, 0x47, 0xa1,
	0xb7, 0xe0, 0xec, 0x10, 0x4f, 0x60, 0xb4, 0x8a, 0xb8, 0x64, 0x47, 0x97, 0x9f, 0x5f, 0x05, 0x06,
	0x21, 0xb4, 0xe1, 0x6c, 0x10, 0xb8, 0xf3, 0x62, 0x3f, 0x10, 0xd1, 0x57, 0x3f, 0x64, 0x07, 0x38,
	0x86, 0xc3, 0xe0, 0x41, 0x70, 0xc9, 0x0c, 0x9c, 0xc0, 0xf1, 0x42, 0x72, 0x2f, 0x0e, 0x24, 0x33,
	0x6f, 0x6f, 0x7e, 0x5d, 0x3f, 0xa9, 0xe6, 0x79, 0x97, 0x39, 0x79, 0xf5, 0xe2, 0x6e, 0x76, 0x19,
	0x3d, 0x16, 0xd5, 0x6f, 0x57, 0x2b, 0x4d, 0x85, 0x2a, 0x69, 0xeb, 0xbe, 0x1d, 0xf6, 0xa9, 0x4a,
	0xf2, 0x42, 0x51, 0xd9, 0x64, 0x47, 0xdd, 0xa0, 0xd7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x92,
	0x6b, 0x1c, 0x75, 0xf8, 0x01, 0x00, 0x00,
}
